{% set name = "luajit-openresty" %}
{% set version = "2.1-20240815" %}
{% set version_under = version.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version_under }}

source:
  url: https://github.com/openresty/luajit2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9e59ec13c301c8b2855838b1248def49ef348a3e7563fabef677431706718145

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libluajit${SHLIB_EXT}  # [unix]
    - luajit -e "print('hello world')"

about:
  home: https://github.com/openresty/luajit2
  license: MIT
  license_family: MIT
  license_file: COPYRIGHT
  summary: OpenResty's Branch of LuaJIT 2
  dev_url: https://github.com/openresty/luajit2

extra:
  recipe-maintainers:
    - danielnachun
