{% set name = "luajit-openresty" %}
{% set version = "2.1-20230911" %}
{% set version_under = version.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version_under }}

source:
  url: https://github.com/openresty/luajit2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d08c23a0c793261cad1775795f258ca2149642eb19d3679a6bbb77582fa1d206

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f $PREFIX/lib/libluajit${SHLIB_EXT}

about:
  home: https://github.com/openresty/luajit2
  license: MIT
  license_family: MIT
  license_file: COPYRIGHT
  summary: OpenResty's Branch of LuaJIT 2
  dev_url: https://github.com/openresty/luajit2

extra:
  recipe-maintainers:
    - danielnachun
