context:
  name: luajit-openresty
  version: 2.1-20241113
  version_under: ${{"version | replace("-", "_")"}}

package:
  name: ${{ name|lower }}
  version: ${{ version_under }}

source:
  url: https://github.com/openresty/luajit2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3b269f3a55c420e5a286bbd6b8ef8a5425dbcb4194fa2beb9e22eea277cd6638

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libluajit${SHLIB_EXT}
      - luajit -e "print('hello world')"

about:
  license: MIT
  license_file: COPYRIGHT
  summary: "OpenResty's Branch of LuaJIT 2"
  homepage: https://github.com/openresty/luajit2
  repository: https://github.com/openresty/luajit2

extra:
  recipe-maintainers:
    - danielnachun
