context:
  version: "2.1-20260114"
  version_under: ${{ version | replace("-", "_") }}

package:
  name: luajit-openresty
  version: ${{ version_under }}

source:
  url: https://github.com/openresty/luajit2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 732b6d7f5f40d637805c0aa7e53c69644372ebff23dbf77f3bf187f8f7fde6f6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make
  run_exports:
    - ${{ pin_subpackage("luajit-openresty") }}
  run_constraints:
    # Luajit should not be installed together with lua 5.1
    - lua <5.1|>=5.2

tests:
  - package_contents:
      bin:
        - luajit
      include:
        - luajit-2.1/lua.h
        - luajit-2.1/luajit.h
      lib:
        - if: win
          then: lua51
          else: luajit
  - script:
      - luajit -v
      - luajit -e "print(package.path)"

about:
  license: MIT
  license_file: COPYRIGHT
  summary: "OpenResty's Branch of LuaJIT 2"
  homepage: https://github.com/openresty/luajit2
  repository: https://github.com/openresty/luajit2

extra:
  recipe-maintainers:
    - danielnachun
    - baszalmstra
