context:
  version: "2.1-20250117"
  version_under: ${{ version | replace("-", "_") }}

package:
  name: luajit-openresty
  version: ${{ version_under }}

source:
  url: https://github.com/openresty/luajit2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 68ff3dc2cc97969f7385679da7c9ff96738aa9cc275fa6bab77316eb3340ea8e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libluajit${SHLIB_EXT}
      - luajit -e "print('hello world')"

about:
  license: MIT
  license_file: COPYRIGHT
  summary: "OpenResty's Branch of LuaJIT 2"
  homepage: https://github.com/openresty/luajit2
  repository: https://github.com/openresty/luajit2

extra:
  recipe-maintainers:
    - danielnachun
